services:
  - type: web
    name: redslippers-valuation
    env: python
    buildCommand: |
      apt-get update && apt-get install -y default-jdk
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --log-level info
