services:
  - type: web
    name: my-fastapi-app
    env: python
    plan: free
    envVars:
      - key: JAVA_HOME
        value: "/usr/lib/jvm/java-11-openjdk-amd64/"
      - key: PATH
        value: "/usr/lib/jvm/java-11-openjdk-amd64/bin:$PATH"
    buildCommand: sudo apt-get update && sudo apt-get install -y default-jdk
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
